### ISSUE TITLE
The link in your profile is dead. 

### ISSUE THREAD

**Issue by mmiscool** [itsAnanth/itsAnanth#1]
<img width="521" alt="image" src="https://github.com/user-attachments/assets/53097dad-b88c-4402-aa39-d7b7e5fcead2" />

**Comment by itsAnanth** [comment]
Yeah i forgot to update it, i got that domain as a part of github student developer pack, it expired last year 🫠🫠

**Comment by itsAnanth** [comment]
Btw your aiCoder project is very dope, i found it from a discord server today

**Comment by mmiscool** [comment]
Sweet. If you run in to any issues using it please feel free to hit me up on discord or open an issue. 
It is very new and still needs some refinement.
